repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
            exclude: \.diff$
          - id: end-of-file-fixer
            exclude: \.diff$
          - id: check-added-large-files
            args: [--maxkb=4096]
          - id: check-yaml
            args: [--allow-multiple-documents]
          - id: check-json
            exclude: ^(.vscode/|.*tsconfig.*\.json$)
          - id: check-toml
          - id: check-merge-conflict
          - id: mixed-line-ending
            args: ["--fix=lf"]
            exclude: \.diff$

    - repo: local
      hooks:
          - id: prettier
            name: Run prettier
            entry: npx prettier --write
            language: system
            files: "\\.(js|ts|json|css|html|ya?ml|md)$"

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.12.2
      hooks:
          - id: ruff
            types_or: [python, pyi, jupyter]
            args: [--fix]
          - id: ruff-format
            types_or: [python, pyi, jupyter]

    - repo: https://github.com/adrienverge/yamllint
      rev: v1.37.1
      hooks:
          - id: yamllint

    - repo: local
      hooks:
          - id: pyright
            name: Run pyright
            entry: env PYRIGHT_PYTHON_FORCE_VERSION=latest uv run pyright
            language: system
            types: [python]
            pass_filenames: false

          - id: ty
            name: Run ty
            entry: uv run ty check
            language: system
            types: [python]
            pass_filenames: false

          - id: check-gitkeep
            name: Check data/.gitkeep exists
            entry: >
                bash -c '[ ! -d data ] || [ -f data/.gitkeep ] ||
                (echo "ERROR: data/.gitkeep is missing!" && exit 1)'
            language: system
            always_run: true
            pass_filenames: false
